-- Import once into an empty Supabase project. Generated from inventario_app.
BEGIN;
--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-27 16:15:00


--
-- TOC entry 229 (class 1255 OID 16444)
-- Name: inventory_touch_product_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.inventory_touch_product_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at := GREATEST(clock_timestamp(), NEW.created_at, OLD.updated_at);
    RETURN NEW;
END;
$$;





--
-- TOC entry 228 (class 1259 OID 16522)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    name text NOT NULL,
    abbreviation text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    sku_counter integer DEFAULT 0 NOT NULL,
    CONSTRAINT categories_name_check CHECK ((length(TRIM(BOTH FROM name)) > 0)),
    CONSTRAINT categories_sku_counter_check CHECK (((sku_counter >= 0) AND (sku_counter <= 25974)))
);



--
-- TOC entry 227 (class 1259 OID 16521)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



--
-- TOC entry 5116 (class 0 OID 0)
-- Dependencies: 227
-- Name: categories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.categories_id_seq OWNED BY public.categories.id;


--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: companies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.companies (
    id bigint NOT NULL,
    name text NOT NULL,
    profile text NOT NULL,
    CONSTRAINT companies_name_not_blank CHECK ((btrim(name) <> ''::text)),
    CONSTRAINT companies_profile_not_blank CHECK ((btrim(profile) <> ''::text))
);



--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16510)
-- Name: movement_changes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movement_changes (
    action_id uuid NOT NULL,
    company_id bigint NOT NULL,
    request jsonb NOT NULL,
    result jsonb NOT NULL
);



--
-- TOC entry 225 (class 1259 OID 16470)
-- Name: movement_lines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movement_lines (
    id bigint NOT NULL,
    movement_code uuid NOT NULL,
    company_id bigint NOT NULL,
    product_id bigint NOT NULL,
    sku text NOT NULL,
    units integer NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    initial_qty integer NOT NULL,
    final_qty integer NOT NULL,
    product_name text NOT NULL,
    unit_price numeric NOT NULL,
    discount_type text,
    discount_value numeric DEFAULT 0 NOT NULL,
    CONSTRAINT movement_lines_check CHECK (((final_qty)::bigint = ((initial_qty)::bigint + (units)::bigint))),
    CONSTRAINT movement_lines_check1 CHECK (((discount_value >= (0)::numeric) AND (discount_value <= (2147483647)::numeric) AND ((discount_type IS NOT NULL) OR (discount_value = (0)::numeric)) AND ((discount_type IS DISTINCT FROM 'percentage'::text) OR (discount_value <= (100)::numeric)))),
    CONSTRAINT movement_lines_discount_type_check CHECK ((discount_type = ANY (ARRAY['fixed'::text, 'percentage'::text]))),
    CONSTRAINT movement_lines_final_qty_check CHECK ((final_qty >= 0)),
    CONSTRAINT movement_lines_initial_qty_check CHECK ((initial_qty >= 0)),
    CONSTRAINT movement_lines_units_check CHECK ((units <> 0))
);



--
-- TOC entry 224 (class 1259 OID 16469)
-- Name: movement_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.movement_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



--
-- TOC entry 5117 (class 0 OID 0)
-- Dependencies: 224
-- Name: movement_lines_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.movement_lines_id_seq OWNED BY public.movement_lines.id;


--
-- TOC entry 223 (class 1259 OID 16448)
-- Name: movements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movements (
    code uuid NOT NULL,
    company_id bigint NOT NULL,
    operation text NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    discount_type text,
    discount_value numeric DEFAULT 0 NOT NULL,
    request jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    display_code character varying(12) NOT NULL,
    revision integer DEFAULT 1 NOT NULL,
    deleted_at timestamp with time zone,
    operation_detail text DEFAULT 'Otros'::text NOT NULL,
    channel text,
    payment_method text,
    discount_scope text DEFAULT 'global'::text NOT NULL,
    "Estado" text DEFAULT 'Pagado'::text NOT NULL,
    CONSTRAINT "movements_Estado_check" CHECK (("Estado" = ANY (ARRAY['Pagado'::text, 'Pendiente de Pago'::text]))),
    CONSTRAINT movements_channel_check CHECK ((channel = ANY (ARRAY['Físico'::text, 'Online'::text]))),
    CONSTRAINT movements_check CHECK (((discount_type IS NOT NULL) OR (discount_value = (0)::numeric))),
    CONSTRAINT movements_check1 CHECK (((discount_type IS DISTINCT FROM 'percentage'::text) OR (discount_value <= (100)::numeric))),
    CONSTRAINT movements_discount_scope_check CHECK ((discount_scope = ANY (ARRAY['global'::text, 'product'::text]))),
    CONSTRAINT movements_discount_type_check CHECK ((discount_type = ANY (ARRAY['fixed'::text, 'percentage'::text]))),
    CONSTRAINT movements_discount_value_check CHECK ((discount_value >= (0)::numeric)),
    CONSTRAINT movements_operation_check CHECK ((operation = ANY (ARRAY['Ingreso'::text, 'Egreso'::text]))),
    CONSTRAINT movements_operation_detail_check CHECK ((((operation = 'Ingreso'::text) AND (operation_detail = ANY (ARRAY['Compra'::text, 'Otros'::text]))) OR ((operation = 'Egreso'::text) AND (operation_detail = ANY (ARRAY['Venta'::text, 'Merma'::text, 'Consumo Interno'::text, 'Otros'::text]))))),
    CONSTRAINT movements_payment_method_check CHECK ((payment_method = ANY (ARRAY['Efectivo'::text, 'Tarjeta'::text, 'Transferencia'::text])))
);



--
-- TOC entry 222 (class 1259 OID 16405)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    company_id bigint NOT NULL,
    name text NOT NULL,
    sku character varying(32) NOT NULL,
    category text NOT NULL,
    qty integer DEFAULT 0 NOT NULL,
    cost integer NOT NULL,
    price integer NOT NULL,
    crit_qty integer NOT NULL,
    low_qty integer NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT products_category_not_blank CHECK ((btrim(category) <> ''::text)),
    CONSTRAINT products_cost_nonnegative CHECK ((cost >= 0)),
    CONSTRAINT products_name_not_blank CHECK ((btrim(name) <> ''::text)),
    CONSTRAINT products_price_nonnegative CHECK ((price >= 0)),
    CONSTRAINT products_qty_nonnegative CHECK ((qty >= 0)),
    CONSTRAINT products_sku_format CHECK (((sku)::text ~ '^[A-Z0-9]+(-[A-Z0-9]+)*$'::text)),
    CONSTRAINT products_thresholds_valid CHECK (((crit_qty >= 0) AND (crit_qty < low_qty))),
    CONSTRAINT products_timestamps_valid CHECK ((updated_at >= created_at))
);



--
-- TOC entry 221 (class 1259 OID 16404)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4891 (class 2604 OID 16525)
-- Name: categories id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories ALTER COLUMN id SET DEFAULT nextval('public.categories_id_seq'::regclass);


--
-- TOC entry 4889 (class 2604 OID 16473)
-- Name: movement_lines id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movement_lines ALTER COLUMN id SET DEFAULT nextval('public.movement_lines_id_seq'::regclass);


--
-- TOC entry 5110 (class 0 OID 16522)
-- Dependencies: 228
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('2', '1', 'Abarrotes', 'ABA', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('3', '1', 'Aceites', 'ACE', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('4', '1', 'Bebidas', 'BEB', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('5', '1', 'Bebidas calientes', 'BEB1', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('6', '1', 'Bebidas en Polvo', 'BEB2', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('7', '1', 'Cereales', 'CER', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('8', '1', 'Condimentos', 'CON', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('9', '1', 'Conservas', 'CON1', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('10', '1', 'Galletas', 'GAL', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('11', '1', 'Lácteos', 'LÁC', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('12', '1', 'Legumbres', 'LEG', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('13', '1', 'Pastas', 'PAS', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('15', '2', 'Aseo', 'ASE', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('16', '2', 'Baño', 'BAÑ', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('17', '2', 'Cocina', 'COC', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('18', '2', 'Electrodomésticos', 'ELE', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('19', '2', 'Mesa', 'MES', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('20', '2', 'Organización', 'ORG', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('22', '3', 'Accesorios', 'ACC', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('23', '3', 'Almacenamiento', 'ALM', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('24', '3', 'Audio', 'AUD', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('25', '3', 'Cables', 'CAB', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('26', '3', 'Conectividad', 'CON', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('27', '3', 'Energía', 'ENE', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('28', '3', 'Periféricos', 'PER', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('30', '4', 'Abrasivos', 'ABR', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('31', '4', 'Accesorios de herramientas', 'ACC', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('32', '4', 'Adhesivos y sellantes', 'ADH', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('33', '4', 'Fijaciones', 'FIJ', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('34', '4', 'Herramientas eléctricas', 'HER', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('35', '4', 'Herramientas manuales', 'HER1', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('36', '4', 'Mantención', 'MAN', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('37', '4', 'Medición', 'MED', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('38', '4', 'Protección personal', 'PRO', '2026-09-13 18:45:16.008433-03', '2026-09-13 18:45:16.008433-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('14', '2', 'Sin Clasificar', 'SIN', '2026-09-13 18:45:16.008433-03', '2026-09-14 18:05:24.030682-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('21', '3', 'Sin Clasificar', 'SIN', '2026-09-13 18:45:16.008433-03', '2026-09-14 18:05:24.030696-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('29', '4', 'Sin Clasificar', 'SIN', '2026-09-13 18:45:16.008433-03', '2026-09-14 18:05:24.030704-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('64', '1', 'Leches en Polvo', 'LEC', '2026-09-24 20:28:08.379755-03', '2026-09-24 20:28:08.379755-03', '0');
INSERT INTO public.categories (id, company_id, name, abbreviation, created_at, updated_at, sku_counter) VALUES ('1', '1', 'Sin Clasificar', 'SIN', '2026-09-13 18:45:16.008433-03', '2026-09-14 18:05:24.030461-03', '1');


--
-- TOC entry 5102 (class 0 OID 16390)
-- Dependencies: 220
-- Data for Name: companies; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.companies (id, name, profile) VALUES ('1', 'Distribuidora Andes Ltda.', 'Distribución mayorista de abarrotes y alimentos no perecibles.');
INSERT INTO public.companies (id, name, profile) VALUES ('2', 'Comercial Maipo SpA', 'Comercio minorista de artículos de cocina, organización y aseo del hogar.');
INSERT INTO public.companies (id, name, profile) VALUES ('3', 'Importadora Pacífic', 'Importación y venta de accesorios electrónicos, conectividad y periféricos.');
INSERT INTO public.companies (id, name, profile) VALUES ('4', 'Suministros Bío Bío', 'Suministros de ferretería, herramientas y protección personal para talleres e industrias.');


--
-- TOC entry 5108 (class 0 OID 16510)
-- Dependencies: 226
-- Data for Name: movement_changes; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5107 (class 0 OID 16470)
-- Dependencies: 225
-- Data for Name: movement_lines; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.movement_lines (id, movement_code, company_id, product_id, sku, units, occurred_at, initial_qty, final_qty, product_name, unit_price, discount_type, discount_value) VALUES ('53', 'dda87af6-4cac-4b39-b21a-442276db43c3', '1', '5', 'AND-0005', '-4', '2026-09-13 18:32:00-03', '30', '26', 'Aceite vegetal botella 1 L', '1890', NULL, '0');
INSERT INTO public.movement_lines (id, movement_code, company_id, product_id, sku, units, occurred_at, initial_qty, final_qty, product_name, unit_price, discount_type, discount_value) VALUES ('6', 'b6300f19-599b-4731-8aa8-e0e6749a2c7b', '1', '5', 'AND-0005', '-2', '2026-09-12 18:15:00-03', '35', '33', 'Aceite vegetal botella 1 L', '1890', NULL, '0');
INSERT INTO public.movement_lines (id, movement_code, company_id, product_id, sku, units, occurred_at, initial_qty, final_qty, product_name, unit_price, discount_type, discount_value) VALUES ('7', 'b6300f19-599b-4731-8aa8-e0e6749a2c7b', '1', '83', 'AND-0022', '-2', '2026-09-12 18:15:00-03', '66', '64', 'Milo 250g', '5000', NULL, '0');
INSERT INTO public.movement_lines (id, movement_code, company_id, product_id, sku, units, occurred_at, initial_qty, final_qty, product_name, unit_price, discount_type, discount_value) VALUES ('13', '460bd5f8-736b-4db0-a0ab-e2a8ac1823ac', '1', '5', 'AND-0005', '-3', '2026-09-12 20:30:00-03', '33', '30', 'Aceite vegetal botella 1 L', '1890', NULL, '0');
INSERT INTO public.movement_lines (id, movement_code, company_id, product_id, sku, units, occurred_at, initial_qty, final_qty, product_name, unit_price, discount_type, discount_value) VALUES ('14', '460bd5f8-736b-4db0-a0ab-e2a8ac1823ac', '1', '83', 'AND-0022', '-3', '2026-09-12 20:30:00-03', '64', '61', 'Milo 250g', '5000', NULL, '0');
INSERT INTO public.movement_lines (id, movement_code, company_id, product_id, sku, units, occurred_at, initial_qty, final_qty, product_name, unit_price, discount_type, discount_value) VALUES ('170', 'd6e7d838-e151-4718-9653-706fe759636c', '1', '10', 'AND-0010', '-3', '2026-09-27 12:58:00-03', '320', '317', 'Atún al agua lata 160 g', '1390', NULL, '0');
INSERT INTO public.movement_lines (id, movement_code, company_id, product_id, sku, units, occurred_at, initial_qty, final_qty, product_name, unit_price, discount_type, discount_value) VALUES ('171', '15c36220-a463-4081-8ce8-f1b4efa98c54', '1', '1', 'AND-0001', '-3', '2026-09-27 13:10:00-03', '240', '237', 'Arroz grado 2 bolsa 1 kg', '1490', NULL, '0');


--
-- TOC entry 5105 (class 0 OID 16448)
-- Dependencies: 223
-- Data for Name: movements; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.movements (code, company_id, operation, occurred_at, discount_type, discount_value, request, created_at, display_code, revision, deleted_at, operation_detail, channel, payment_method, discount_scope, "Estado") VALUES ('b6300f19-599b-4731-8aa8-e0e6749a2c7b', '1', 'Egreso', '2026-09-12 18:15:00-03', 'fixed', '1000', '{"items": [{"units": 2, "product_id": "5"}, {"units": 2, "product_id": "83"}], "discount": {"type": "fixed", "value": 1000}, "operation": "Egreso", "occurred_at": "2026-09-12T21:15:00.000Z"}', '2026-09-12 18:15:58.492222-03', '6d3f82be96de', '1', NULL, 'Otros', NULL, NULL, 'global', 'Pagado');
INSERT INTO public.movements (code, company_id, operation, occurred_at, discount_type, discount_value, request, created_at, display_code, revision, deleted_at, operation_detail, channel, payment_method, discount_scope, "Estado") VALUES ('460bd5f8-736b-4db0-a0ab-e2a8ac1823ac', '1', 'Egreso', '2026-09-12 20:30:00-03', 'percentage', '10', '{"items": [{"units": 3, "product_id": "5"}, {"units": 3, "product_id": "83"}], "discount": {"type": "percentage", "value": 10}, "operation": "Egreso", "occurred_at": "2026-09-12T23:30:00.000Z"}', '2026-09-12 20:32:41.324939-03', '6e61dc754b8f', '1', NULL, 'Otros', NULL, NULL, 'global', 'Pagado');
INSERT INTO public.movements (code, company_id, operation, occurred_at, discount_type, discount_value, request, created_at, display_code, revision, deleted_at, operation_detail, channel, payment_method, discount_scope, "Estado") VALUES ('dda87af6-4cac-4b39-b21a-442276db43c3', '1', 'Egreso', '2026-09-13 18:32:00-03', NULL, '0', '{"items": [{"units": 4, "product_id": "5"}], "discount": null, "operation": "Egreso", "occurred_at": "2026-09-13T21:32:00.000Z"}', '2026-09-13 18:32:40.066968-03', 'f93111ff4a60', '1', NULL, 'Otros', NULL, NULL, 'global', 'Pagado');
INSERT INTO public.movements (code, company_id, operation, occurred_at, discount_type, discount_value, request, created_at, display_code, revision, deleted_at, operation_detail, channel, payment_method, discount_scope, "Estado") VALUES ('d6e7d838-e151-4718-9653-706fe759636c', '1', 'Egreso', '2026-09-27 12:58:00-03', 'percentage', '4', '{"items": [{"units": 3, "discount": null, "product_id": "10"}], "channel": "Físico", "discount": {"type": "percentage", "scope": "global", "value": 4}, "operation": "Egreso", "occurred_at": "2026-09-27T15:58:00.000Z", "payment_method": "Tarjeta", "operation_detail": "Venta"}', '2026-09-27 12:58:54.447752-03', 'd33ae78ad0bf', '1', NULL, 'Venta', 'Físico', 'Tarjeta', 'global', 'Pagado');
INSERT INTO public.movements (code, company_id, operation, occurred_at, discount_type, discount_value, request, created_at, display_code, revision, deleted_at, operation_detail, channel, payment_method, discount_scope, "Estado") VALUES ('15c36220-a463-4081-8ce8-f1b4efa98c54', '1', 'Egreso', '2026-09-27 13:10:00-03', NULL, '0', '{"items": [{"units": 3, "discount": null, "product_id": "1"}], "channel": "Online", "discount": null, "operation": "Egreso", "occurred_at": "2026-09-27T16:10:00.000Z", "payment_method": "Tarjeta", "operation_detail": "Venta"}', '2026-09-27 13:10:11.868515-03', '63a1601a2b15', '1', NULL, 'Venta', 'Online', 'Tarjeta', 'global', 'Pagado');


--
-- TOC entry 5104 (class 0 OID 16405)
-- Dependencies: 222
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('2', '1', 'Fideos espirales paquete 400 g', 'AND-0002', 'Pastas', '360', '520', '790', '60', '150', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('3', '1', 'Harina sin polvos bolsa 1 kg', 'AND-0003', 'Abarrotes', '180', '780', '1190', '30', '80', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('4', '1', 'Azúcar granulada bolsa 1 kg', 'AND-0004', 'Abarrotes', '210', '920', '1390', '40', '100', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('10', '1', 'Atún al agua lata 160 g', 'AND-0010', 'Conservas', '317', '920', '1390', '50', '120', '2026-09-08 03:13:52.22476-03', '2026-09-27 12:58:54.466906-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('6', '1', 'Sal fina bolsa 1 kg', 'AND-0006', 'Condimentos', '150', '330', '590', '20', '60', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('7', '1', 'Lentejas bolsa 1 kg', 'AND-0007', 'Legumbres', '65', '1450', '2090', '25', '70', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('8', '1', 'Porotos tórtola bolsa 1 kg', 'AND-0008', 'Legumbres', '95', '2200', '3090', '20', '50', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('9', '1', 'Garbanzos bolsa 1 kg', 'AND-0009', 'Legumbres', '48', '1800', '2590', '20', '50', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('11', '1', 'Jurel al natural lata 425 g', 'AND-0011', 'Conservas', '0', '1350', '1990', '30', '80', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('12', '1', 'Salsa de tomate sachet 200 g', 'AND-0012', 'Conservas', '480', '290', '490', '80', '200', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('13', '1', 'Duraznos en mitades lata 820 g', 'AND-0013', 'Conservas', '72', '1500', '2190', '15', '40', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('14', '1', 'Leche entera UHT caja 1 L', 'AND-0014', 'Lácteos', '420', '820', '1190', '60', '180', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('15', '1', 'Leche en polvo bolsa 800 g', 'AND-0015', 'Lácteos', '18', '4800', '6490', '20', '45', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('16', '1', 'Café instantáneo frasco 170 g', 'AND-0016', 'Bebidas calientes', '55', '3500', '4990', '15', '40', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('17', '1', 'Té negro caja 100 bolsas', 'AND-0017', 'Bebidas calientes', '110', '1450', '2190', '20', '60', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('18', '1', 'Avena tradicional bolsa 1 kg', 'AND-0018', 'Cereales', '83', '1250', '1890', '20', '50', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('19', '1', 'Galletas de soda paquete 180 g', 'AND-0019', 'Galletas', '145', '480', '790', '30', '90', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('20', '1', 'Agua mineral sin gas botella 1.5 L', 'AND-0020', 'Bebidas', '600', '390', '690', '100', '250', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('21', '2', 'Set de ollas antiadherentes 5 piezas', 'MAI-0001', 'Cocina', '32', '18500', '29900', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('22', '2', 'Sartén antiadherente 28 cm', 'MAI-0002', 'Cocina', '46', '6200', '10990', '8', '20', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('23', '2', 'Hervidor eléctrico 1.7 L', 'MAI-0003', 'Electrodomésticos', '11', '8500', '14990', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('24', '2', 'Tostador eléctrico 2 rebanadas', 'MAI-0004', 'Electrodomésticos', '24', '9800', '16990', '4', '12', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('25', '2', 'Vajilla de cerámica 12 piezas', 'MAI-0005', 'Mesa', '18', '14000', '23990', '3', '10', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('26', '2', 'Set de cubiertos 24 piezas', 'MAI-0006', 'Mesa', '35', '7500', '12990', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('27', '2', 'Set de vasos de vidrio 6 unidades', 'MAI-0007', 'Mesa', '60', '3200', '5990', '10', '25', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('28', '2', 'Tabla de cortar bambú 35 cm', 'MAI-0008', 'Cocina', '42', '2800', '4990', '8', '20', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('29', '2', 'Contenedor hermético 1.5 L', 'MAI-0009', 'Organización', '95', '1600', '2990', '15', '40', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('30', '2', 'Organizador modular set 6 cajas', 'MAI-0010', 'Organización', '4', '9800', '16900', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('31', '2', 'Canasto para ropa 45 L', 'MAI-0011', 'Organización', '28', '4500', '7990', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('32', '2', 'Zapatero de 4 niveles', 'MAI-0012', 'Organización', '16', '8500', '14990', '3', '10', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('33', '2', 'Escoba con mango 120 cm', 'MAI-0013', 'Aseo', '80', '1400', '2790', '15', '35', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('34', '2', 'Pala para basura con mango', 'MAI-0014', 'Aseo', '54', '1200', '2290', '10', '25', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('35', '2', 'Trapero de microfibra con mango', 'MAI-0015', 'Aseo', '38', '2200', '3990', '8', '20', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('36', '2', 'Balde con escurridor 14 L', 'MAI-0016', 'Aseo', '0', '3800', '6990', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('37', '2', 'Paños de microfibra set 4 unidades', 'MAI-0017', 'Aseo', '120', '1100', '2490', '20', '50', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('38', '2', 'Basurero con pedal 12 L', 'MAI-0018', 'Aseo', '22', '5800', '9990', '4', '12', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('39', '2', 'Cortina de baño 180 x 180 cm', 'MAI-0019', 'Baño', '31', '2900', '5490', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('40', '2', 'Toalla de baño algodón 70 x 140 cm', 'MAI-0020', 'Baño', '7', '4200', '7990', '8', '20', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('41', '3', 'Audífonos Bluetooth intraaurales', 'PAC-0001', 'Audio', '85', '7800', '14990', '15', '40', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('42', '3', 'Parlante Bluetooth portátil 10 W', 'PAC-0002', 'Audio', '42', '10500', '19990', '8', '25', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('43', '3', 'Audífonos con micrófono USB', 'PAC-0003', 'Audio', '28', '6500', '12990', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('44', '3', 'Cable USB-C a USB-C 1 m 60 W', 'PAC-0004', 'Cables', '250', '1200', '3990', '40', '100', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('45', '3', 'Cable HDMI 2 m', 'PAC-0005', 'Cables', '140', '1800', '4990', '25', '60', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('46', '3', 'Cargador USB-C 30 W', 'PAC-0006', 'Energía', '60', '4500', '9990', '10', '30', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('47', '3', 'Batería externa 10000 mAh', 'PAC-0007', 'Energía', '9', '6800', '14990', '10', '30', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('48', '3', 'Cargador inalámbrico 15 W', 'PAC-0008', 'Energía', '34', '4200', '8990', '6', '20', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('49', '3', 'Mouse inalámbrico 1600 dpi', 'PAC-0009', 'Periféricos', '110', '2800', '6990', '20', '50', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('50', '3', 'Teclado USB español', 'PAC-0010', 'Periféricos', '58', '4300', '9990', '10', '30', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('51', '3', 'Kit teclado y mouse inalámbrico', 'PAC-0011', 'Periféricos', '26', '8900', '17990', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('52', '3', 'Cámara web Full HD 1080p', 'PAC-0012', 'Periféricos', '17', '9800', '21990', '5', '20', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('53', '3', 'Hub USB-C 6 en 1', 'PAC-0013', 'Conectividad', '45', '8500', '18990', '8', '25', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('54', '3', 'Adaptador USB Wi-Fi AC600', 'PAC-0014', 'Conectividad', '64', '3900', '8990', '10', '30', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('55', '3', 'Repetidor Wi-Fi doble banda AC1200', 'PAC-0015', 'Conectividad', '0', '12000', '24990', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('56', '3', 'Soporte plegable para notebook', 'PAC-0016', 'Accesorios', '72', '3500', '8990', '12', '35', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('57', '3', 'Base refrigerante para notebook', 'PAC-0017', 'Accesorios', '39', '6200', '12990', '6', '20', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('58', '3', 'Memoria microSD 128 GB clase 10', 'PAC-0018', 'Almacenamiento', '96', '5800', '11990', '15', '40', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('59', '3', 'Unidad flash USB 64 GB', 'PAC-0019', 'Almacenamiento', '180', '2400', '5990', '30', '80', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('60', '3', 'Disco SSD externo 500 GB USB-C', 'PAC-0020', 'Almacenamiento', '4', '28500', '44990', '5', '12', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('61', '4', 'Guantes de seguridad nitrilo par', 'BIO-0001', 'Protección personal', '240', '1100', '2290', '40', '100', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('62', '4', 'Lentes de seguridad transparentes', 'BIO-0002', 'Protección personal', '150', '1500', '3290', '25', '60', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('1', '1', 'Arroz grado 2 bolsa 1 kg', 'AND-0001', 'Abarrotes', '237', '1050', '1490', '40', '100', '2026-09-08 03:13:52.22476-03', '2026-09-27 13:10:11.874843-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('63', '4', 'Casco de seguridad ajustable', 'BIO-0003', 'Protección personal', '65', '3200', '5990', '10', '30', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('64', '4', 'Protector auditivo tipo copa', 'BIO-0004', 'Protección personal', '38', '5800', '9990', '8', '20', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('65', '4', 'Respirador reutilizable medio rostro sin filtros', 'BIO-0005', 'Protección personal', '12', '11500', '19990', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('66', '4', 'Chaleco reflectante talla L', 'BIO-0006', 'Protección personal', '90', '2600', '4990', '15', '40', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('67', '4', 'Zapatos de seguridad talla 42 par', 'BIO-0007', 'Protección personal', '6', '22500', '36990', '8', '20', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('68', '4', 'Taladro percutor 750 W', 'BIO-0008', 'Herramientas eléctricas', '18', '32000', '54990', '3', '10', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('69', '4', 'Esmeril angular 115 mm 850 W', 'BIO-0009', 'Herramientas eléctricas', '22', '24500', '42990', '4', '12', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('70', '4', 'Disco de corte metal 115 mm', 'BIO-0010', 'Abrasivos', '320', '650', '1490', '50', '150', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('71', '4', 'Disco flap grano 80 de 115 mm', 'BIO-0011', 'Abrasivos', '140', '1200', '2490', '25', '60', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('72', '4', 'Juego de brocas HSS 13 piezas', 'BIO-0012', 'Accesorios de herramientas', '35', '5200', '9990', '6', '20', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('73', '4', 'Llave ajustable 10 pulgadas', 'BIO-0013', 'Herramientas manuales', '48', '4300', '7990', '8', '25', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('74', '4', 'Alicate universal 8 pulgadas', 'BIO-0014', 'Herramientas manuales', '52', '3600', '6990', '10', '25', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('75', '4', 'Juego de destornilladores 6 piezas', 'BIO-0015', 'Herramientas manuales', '31', '4900', '8990', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('76', '4', 'Huincha de medir 5 m', 'BIO-0016', 'Medición', '76', '2200', '4490', '12', '35', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('77', '4', 'Pernos hexagonales M8 x 40 mm caja 100', 'BIO-0017', 'Fijaciones', '27', '6500', '10990', '5', '15', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('78', '4', 'Tarugos de nylon 8 mm bolsa 100', 'BIO-0018', 'Fijaciones', '0', '1600', '3290', '10', '30', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('79', '4', 'Silicona neutra transparente cartucho 300 ml', 'BIO-0019', 'Adhesivos y sellantes', '64', '2400', '4490', '12', '35', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('80', '4', 'Lubricante multiuso aerosol 400 ml', 'BIO-0020', 'Mantención', '19', '3100', '5990', '10', '30', '2026-09-08 03:13:52.22476-03', '2026-09-08 03:13:52.22476-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('83', '1', 'Milo 250g', 'AND-0022', 'Bebidas en Polvo', '61', '2500', '5000', '10', '25', '2026-09-09 17:30:00-03', '2026-09-12 20:32:41.343629-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('5', '1', 'Aceite vegetal botella 1 L', 'AND-0005', 'Aceites', '26', '1350', '1890', '40', '100', '2026-09-08 03:13:52.22476-03', '2026-09-13 18:32:40.080324-03');
INSERT INTO public.products (id, company_id, name, sku, category, qty, cost, price, crit_qty, low_qty, created_at, updated_at) VALUES ('118', '1', 'Flan de Vainilla 50g', 'SINA001', 'Sin Clasificar', '40', '250', '600', '15', '20', '2026-09-14 19:13:00-03', '2026-09-14 19:13:00-03');


--
-- TOC entry 5118 (class 0 OID 0)
-- Dependencies: 227
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 64, true);


--
-- TOC entry 5119 (class 0 OID 0)
-- Dependencies: 219
-- Name: companies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.companies_id_seq', 4, true);


--
-- TOC entry 5120 (class 0 OID 0)
-- Dependencies: 224
-- Name: movement_lines_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movement_lines_id_seq', 173, true);


--
-- TOC entry 5121 (class 0 OID 0)
-- Dependencies: 221
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 134, true);


--
-- TOC entry 4944 (class 2606 OID 16542)
-- Name: categories categories_company_id_abbreviation_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_company_id_abbreviation_key UNIQUE (company_id, abbreviation);


--
-- TOC entry 4946 (class 2606 OID 16540)
-- Name: categories categories_company_id_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_company_id_name_key UNIQUE (company_id, name);


--
-- TOC entry 4948 (class 2606 OID 16538)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4924 (class 2606 OID 16403)
-- Name: companies companies_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_name_key UNIQUE (name);


--
-- TOC entry 4926 (class 2606 OID 16401)
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- TOC entry 4942 (class 2606 OID 16520)
-- Name: movement_changes movement_changes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movement_changes
    ADD CONSTRAINT movement_changes_pkey PRIMARY KEY (action_id);


--
-- TOC entry 4938 (class 2606 OID 16492)
-- Name: movement_lines movement_lines_movement_code_product_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movement_lines
    ADD CONSTRAINT movement_lines_movement_code_product_id_key UNIQUE (movement_code, product_id);


--
-- TOC entry 4940 (class 2606 OID 16490)
-- Name: movement_lines movement_lines_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movement_lines
    ADD CONSTRAINT movement_lines_pkey PRIMARY KEY (id);


--
-- TOC entry 4936 (class 2606 OID 16468)
-- Name: movements movements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movements
    ADD CONSTRAINT movements_pkey PRIMARY KEY (code);


--
-- TOC entry 4930 (class 2606 OID 16434)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 4932 (class 2606 OID 16436)
-- Name: products products_sku_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_sku_key UNIQUE (sku);


--
-- TOC entry 4933 (class 1259 OID 16503)
-- Name: movements_company_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX movements_company_date ON public.movements USING btree (company_id, created_at DESC);


--
-- TOC entry 4934 (class 1259 OID 16630)
-- Name: movements_display_code; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX movements_display_code ON public.movements USING btree (display_code);


--
-- TOC entry 4927 (class 1259 OID 16442)
-- Name: products_company_category_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_company_category_idx ON public.products USING btree (company_id, category);


--
-- TOC entry 4928 (class 1259 OID 16443)
-- Name: products_company_qty_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_company_qty_idx ON public.products USING btree (company_id, qty);


--
-- TOC entry 4953 (class 2620 OID 16445)
-- Name: products products_touch_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER products_touch_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.inventory_touch_product_updated_at();


--
-- TOC entry 4951 (class 2606 OID 16493)
-- Name: movement_lines movement_lines_movement_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movement_lines
    ADD CONSTRAINT movement_lines_movement_code_fkey FOREIGN KEY (movement_code) REFERENCES public.movements(code);


--
-- TOC entry 4952 (class 2606 OID 16498)
-- Name: movement_lines movement_lines_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movement_lines
    ADD CONSTRAINT movement_lines_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- TOC entry 4949 (class 2606 OID 16543)
-- Name: products products_category_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_category_fk FOREIGN KEY (company_id, category) REFERENCES public.categories(company_id, name) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4950 (class 2606 OID 16437)
-- Name: products products_company_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE RESTRICT;


-- Completed on 2026-09-27 16:15:00

--
-- PostgreSQL database dump complete
--


ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.categories FROM anon, authenticated;
GRANT ALL ON public.categories TO service_role;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.companies FROM anon, authenticated;
GRANT ALL ON public.companies TO service_role;
ALTER TABLE public.movement_changes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.movement_changes FROM anon, authenticated;
GRANT ALL ON public.movement_changes TO service_role;
ALTER TABLE public.movement_lines ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.movement_lines FROM anon, authenticated;
GRANT ALL ON public.movement_lines TO service_role;
ALTER TABLE public.movements ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.movements FROM anon, authenticated;
GRANT ALL ON public.movements TO service_role;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.products FROM anon, authenticated;
GRANT ALL ON public.products TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
COMMIT;
