BEGIN;

CREATE TABLE public.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES public.companies(id),
  name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 120),
  phone text CHECK (phone IS NULL OR (length(phone) <= 32 AND phone ~ '^\+?[0-9 ().-]+$' AND length(regexp_replace(phone, '[^0-9]', '', 'g')) BETWEEN 7 AND 15)),
  email text CHECK (email IS NULL OR (length(email) <= 254 AND email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')),
  address text CHECK (address IS NULL OR length(address) <= 300),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_id, id)
);
CREATE INDEX customers_company_name ON public.customers(company_id, name, id);
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.customers FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.customers TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.customers_id_seq TO service_role;

ALTER TABLE public.movements ADD COLUMN customer_id bigint;
ALTER TABLE public.movements ADD CONSTRAINT movements_customer_company_fk
  FOREIGN KEY (company_id, customer_id) REFERENCES public.customers(company_id, id);

CREATE FUNCTION public.pymio_customer(company bigint, payload jsonb, method text) RETURNS jsonb
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public, pg_temp AS $$
DECLARE customer public.customers;
BEGIN
  IF method = 'list' THEN
    RETURN (SELECT coalesce(jsonb_agg(jsonb_build_object('id', id::text, 'name', name, 'phone', phone, 'email', email, 'address', address) ORDER BY name, id), '[]'::jsonb)
            FROM public.customers WHERE company_id = company);
  ELSIF method = 'create' THEN
    INSERT INTO public.customers(company_id, name, phone, email, address)
    VALUES (company, btrim(payload->>'name'), nullif(btrim(payload->>'phone'), ''),
            nullif(btrim(payload->>'email'), ''), nullif(btrim(payload->>'address'), ''))
    RETURNING * INTO customer;
    RETURN jsonb_build_object('id', customer.id::text, 'name', customer.name, 'phone', customer.phone, 'email', customer.email, 'address', customer.address);
  END IF;
  RAISE SQLSTATE 'PT400' USING MESSAGE = 'Operación de cliente inválida.';
END $$;

CREATE OR REPLACE FUNCTION public.pymio_api(operation text, company bigint, payload jsonb DEFAULT '{}') RETURNS jsonb
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public, pg_temp AS $$
DECLARE result jsonb; selected_customer bigint; request jsonb;
BEGIN
  IF company IS NULL OR company < 1 THEN RAISE SQLSTATE 'PT400' USING MESSAGE = 'Empresa inválida.'; END IF;
  IF operation IN ('product.list','product.history','product.create','product.update','product.delete') THEN
    RETURN public.pymio_product(company, payload, split_part(operation, '.', 2));
  ELSIF operation IN ('category.get','category.post','category.put','category.delete') THEN
    RETURN public.pymio_category(company, payload, split_part(operation, '.', 2));
  ELSIF operation IN ('customer.list','customer.create') THEN
    RETURN public.pymio_customer(company, payload, split_part(operation, '.', 2));
  ELSIF operation = 'movement.list' THEN
    RETURN (SELECT coalesce(jsonb_agg(entry || jsonb_build_object('customer_id', m.customer_id::text, 'customer_name', c.name) ORDER BY ord), '[]'::jsonb)
            FROM jsonb_array_elements(public.pymio_list(company, payload)) WITH ORDINALITY AS listed(entry, ord)
            LEFT JOIN public.movements m ON m.company_id = company AND m.display_code = entry->>'code'
            LEFT JOIN public.customers c ON c.company_id = company AND c.id = m.customer_id);
  ELSIF operation IN ('movement.create','movement.change') THEN
    request := CASE WHEN operation = 'movement.create' THEN payload->'request' ELSE payload->'replacement' END;
    IF request IS NOT NULL AND request <> 'null'::jsonb THEN
      IF request->>'customer_id' IS NOT NULL THEN
        IF request->>'operation_detail' IS DISTINCT FROM 'Venta' OR request->>'customer_id' !~ '^[1-9][0-9]{0,18}$' THEN
          RAISE SQLSTATE 'PT400' USING MESSAGE = 'Selecciona un cliente válido para la venta.';
        END IF;
        selected_customer := (request->>'customer_id')::bigint;
        IF NOT EXISTS (SELECT 1 FROM public.customers WHERE company_id = company AND id = selected_customer) THEN
          RAISE SQLSTATE 'PT400' USING MESSAGE = 'El cliente no existe o no pertenece a esta empresa.';
        END IF;
      END IF;
    END IF;
    result := public.pymio_movement(company, payload, split_part(operation, '.', 2));
    IF request IS NOT NULL AND request <> 'null'::jsonb THEN
      IF operation = 'movement.create' THEN
        UPDATE public.movements SET customer_id = selected_customer
        WHERE company_id = company AND code = (payload->>'code')::uuid;
      ELSE
        UPDATE public.movements SET customer_id = selected_customer
        WHERE company_id = company AND display_code = payload->>'displayCode' AND deleted_at IS NULL;
      END IF;
    END IF;
    RETURN result;
  END IF;
  RAISE SQLSTATE 'PT400' USING MESSAGE = 'Operación inválida.';
END $$;

REVOKE ALL ON FUNCTION public.pymio_customer(bigint, jsonb, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.pymio_customer(bigint, jsonb, text) TO service_role;
NOTIFY pgrst, 'reload schema';
COMMIT;
